# Generated by Django 5.2 on 2025-05-01 00:51

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('flight_number', models.IntegerField(blank=True, null=True)),
                ('departure_airport', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_airport', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gate', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('membership_level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(blank=True, max_length=8, null=True)),
                ('min_points_required', models.IntegerField(blank=True, null=True)),
                ('perks_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'membership_level',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('relationship', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='membership_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membershiplevel'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('read_status', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('booked_at', models.DateTimeField()),
                ('seat_num', models.CharField(blank=True, max_length=10, null=True)),
                ('priority_boarding', models.IntegerField(blank=True, null=True)),
                ('disability_assist', models.IntegerField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.passenger')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=25, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=7, null=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ticket')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.flight')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ticket')),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
    ]
