# Generated by Django 5.2 on 2025-05-01 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_membershiplevel_membership_level_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='disability_assist',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flight'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority_boarding',
            field=models.BooleanField(default=False),
        ),
    ]
