# Generated by Django 5.2 on 2025-05-01 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ticket_disability_assist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='points',
            new_name='membership_points',
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='membership_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.membershiplevel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
