# Generated by Django 5.2 on 2025-05-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_points_passenger_membership_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='accommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='taxi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booked_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
