# Generated by Django 5.2.5 on 2025-08-12 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_flight_to_traintrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='flight',
            field=models.ForeignKey(blank=True, db_column='flight_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.traintrip'),
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='flight',
            new_name='train_trip',
        ),
        migrations.AlterField(
            model_name='traintrip',
            name='aircraft_type',
            field=models.CharField(blank=True, db_column='aircraft_type', max_length=50, null=True),
        ),
        migrations.RenameField(
            model_name='traintrip',
            old_name='aircraft_type',
            new_name='consist_type',
        ),
        migrations.AlterField(
            model_name='traintrip',
            name='arrival_airport',
            field=models.CharField(blank=True, db_column='arrival_airport', max_length=50, null=True),
        ),
        migrations.RenameField(
            model_name='traintrip',
            old_name='arrival_airport',
            new_name='destination_station',
        ),
        migrations.AlterField(
            model_name='traintrip',
            name='gate',
            field=models.CharField(blank=True, db_column='gate', max_length=25, null=True),
        ),
        migrations.RenameField(
            model_name='traintrip',
            old_name='gate',
            new_name='platform',
        ),
        migrations.AlterField(
            model_name='traintrip',
            name='flight_number',
            field=models.IntegerField(blank=True, db_column='flight_number', null=True),
        ),
        migrations.RenameField(
            model_name='traintrip',
            old_name='flight_number',
            new_name='service_number',
        ),
        migrations.AlterField(
            model_name='traintrip',
            name='flight_id',
            field=models.CharField(db_column='flight_id', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='traintrip',
            old_name='flight_id',
            new_name='trip_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='traintrip',
            name='departure_airport',
        ),
        migrations.AddField(
            model_name='traintrip',
            name='origin_station',
            field=models.CharField(blank=True, db_column='departure_airport', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('check', 'Check'), ('cash', 'Cash')], max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=4)),
                ('seat_number', models.CharField(max_length=6)),
                ('travel_class', models.CharField(choices=[('standard', 'Standard'), ('first', 'First'), ('sleeper', 'Sleeper')], max_length=16)),
                ('train_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.traintrip')),
            ],
        ),
    ]
